### ISSUE TITLE
Are there some tutorials about steam client hack?

### ISSUE THREAD

**Issue by fkysly** [Maclay74/steam-patch#9]
This project is cool, but I want to modify this to achieve some features about my own needs. I can learn Rust Language to write, could you tell my more about this tutorial about hack steam client, any tutorial or blog? Thanks a lot.

**Comment by Maclay74** [comment]
Well, since the steam client is just a CEF application, you can reverse engineer it using Chrome developer console. 
You'd need also to understand some concepts of webpack, as it's used to build the app.  

I'd suggest checking out Decky Loader documentation and source code, there are some pieces of information about how the client work.

If there is something more specific you'd want to know, let me know.
